# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x0b\x63hatservice\"0\n\x0b\x43hatRequest\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x0f\n\x07history\x18\x02 \x03(\t\"\x1b\n\tChatReply\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t2K\n\x0b\x43hatService\x12<\n\x04\x63hat\x12\x18.chatservice.ChatRequest\x1a\x16.chatservice.ChatReply\"\x00\x30\x01\x42\x05\xa2\x02\x02\x43Sb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\242\002\002CS'
  _CHATREQUEST._serialized_start=27
  _CHATREQUEST._serialized_end=75
  _CHATREPLY._serialized_start=77
  _CHATREPLY._serialized_end=104
  _CHATSERVICE._serialized_start=106
  _CHATSERVICE._serialized_end=181
# @@protoc_insertion_point(module_scope)
